"""remove condizione field

Revision ID: 81577bed3662
Revises: c955d11f008d
Create Date: 2026-02-02 12:18:05.379230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81577bed3662'
down_revision = 'c955d11f008d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_column('condizione')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condizione', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))

    # ### end Alembic commands ###
