"""Initial migration

Revision ID: c61c338a74c5
Revises: 
Create Date: 2026-02-02 10:47:08.189116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61c338a74c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('squadra', sa.String(length=100), nullable=False),
    sa.Column('campionato', sa.String(length=100), nullable=False),
    sa.Column('taglia', sa.String(length=10), nullable=False),
    sa.Column('colore', sa.String(length=50), nullable=False),
    sa.Column('stagione', sa.String(length=20), nullable=False),
    sa.Column('tipologia', sa.String(length=50), nullable=False),
    sa.Column('player_issued', sa.Boolean(), nullable=True),
    sa.Column('nazionale', sa.Boolean(), nullable=True),
    sa.Column('prezzo_pagato', sa.Float(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shirt_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shirt_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shirt_id'], ['shirts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shirt_images')
    op.drop_table('shirts')
    # ### end Alembic commands ###
