"""add condizione and maniche

Revision ID: c955d11f008d
Revises: c61c338a74c5
Create Date: 2026-02-02 12:15:26.518748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c955d11f008d'
down_revision = 'c61c338a74c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condizione', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('maniche', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_column('maniche')
        batch_op.drop_column('condizione')

    # ### end Alembic commands ###
