"""add player_name field to shirts

Revision ID: d556f7055946
Revises: 81577bed3662
Create Date: 2026-02-03 09:10:02.144824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd556f7055946'
down_revision = '81577bed3662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirts', schema=None) as batch_op:
        batch_op.drop_column('player_name')
    # ### end Alembic commands ###
